In [1]:
import numpy as np 

In [2]:
arrayex5=np.array((12,13,14))
arrayex5

array([12, 13, 14])

In [3]:
import numpy as np
arr=np.array([10,20,30,40,50])
mean_val=np.mean(arr)
std_dev=np.std(arr)
max_val=np.max(arr)
min_val=np.min(arr)
print("Array:",arr)
print("mean:",mean_val)
print("standard Deviation:",std_dev)
print("Maximum:",max_val)
print("Minimum:",min_val)

Array: [10 20 30 40 50]
mean: 30.0
standard Deviation: 14.142135623730951
Maximum: 50
Minimum: 10


In [7]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=np.dot(A,B)
print("matrix A:/n",A)
print("matrix B:/n",B)
print("matix multiplication (A*B):/n",C)

matrix A:/n [[1 2]
 [3 4]]
matrix B:/n [[5 6]
 [7 8]]
matix multiplication (A*B):/n [[19 22]
 [43 50]]


array1=np.array([1,2,3,4,5])
array1
print(array1.ndim)

In [9]:
array1=np.array([1,2,3,4,5])
array1
print(array1.ndim)

1


In [10]:
arrex=np.array([1,2,3,4])
arrex

array([1, 2, 3, 4])

In [11]:
arrex.shape

(4,)

In [24]:
A=np.array([1,2])
A
print(A[1])

2


In [25]:
array7=np.array([[1,2],[3.3,4]])
array7

array([[1. , 2. ],
       [3.3, 4. ]])

In [26]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [29]:
ch_arr2=np.array(['supervised','unisupervised','semi-supervised','reinforcment'])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unisupervised', 'semi-supervised', 'reinforcment'],
      dtype='<U15')

In [ ]:
cleaned_arr=np.char.replace(low_arr,"")